const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"
const USER_LOGOUT = "USER_LOGOUT"

export {USER_LOGIN_REQUEST, 
        USER_LOGIN_SUCCESS, 
        USER_LOGIN_FAILED,
        USER_LOGOUT,
    }